from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0002_add_product_description"
down_revision = "0001_create_products"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("products") as batch_op:
        batch_op.add_column(sa.Column("description", sa.String(length=255), nullable=True))

    products = sa.table(
        "products",
        sa.column("id", sa.Integer()),
        sa.column("title", sa.String(length=120)),
        sa.column("description", sa.String(length=255)),
    )
    connection = op.get_bind()
    existing_rows = connection.execute(sa.select(products.c.id, products.c.title)).all()

    for row in existing_rows:
        connection.execute(
            products.update()
            .where(products.c.id == row.id)
            .values(description=f"Autogenerated description for {row.title}.")
        )

    with op.batch_alter_table("products") as batch_op:
        batch_op.alter_column("description", existing_type=sa.String(length=255), nullable=False)


def downgrade() -> None:
    with op.batch_alter_table("products") as batch_op:
        batch_op.drop_column("description")
